"""
Sample offers data for the multi-tenant MCP server.

This module contains the offer data used by the offers MCP server.
In production, this would be replaced with PostgreSQL queries.
"""

from typing import List, Dict, Any

OFFERS: List[Dict[str, Any]] = [
    {
        "businessId": "bTCz63K65g2o8irCxQuiRCRwOro1m7O4XyUF3Nxb_-Y=",
        "url": "https://www.onehourheatandair.com/lees-summit/about-us/what-to-expect/",
        "serviceCategory": "Emergency HVAC Service",
        "discountType": "amount",
        "discountValue": None,
        "priceCurrency": "USD",
        "price": None,
        "conditions": "Not valid with other offers.",
        "expirationDate": "2025-12-31",
        "stackable": None,
        "minimumPurchase": None,
        "description": "Get a free service call with any repair when you schedule with us!",
        "offerSource": "installer",
        "redemptionInstructions": "Call (816) 354-1077 to schedule and mention this offer.",
        "offerFeatures": ["free service call with repair"],
        "businessName": "One Hour Heating & Air Conditioning of Lee's Summit",
        "city": "Lee's Summit",
        "county": "Jackson County",
        "state": "MO",
        "zipcode": "64063",
        "location": None,
        "market": "Kansas City, MO-KS Metropolitan Statistical Area",
        "size": "Medium-to-Large",
    },
    {
        "businessId": "bBrP89H32x7y4krCxTujRDRxNqp1m5O8YzUG2Nxc_-W=",
        "url": "https://www.bakerbrothers.com/plumbing-services",
        "serviceCategory": "Plumbing",
        "discountType": "amount",
        "discountValue": 50,
        "priceCurrency": "USD",
        "price": None,
        "conditions": "Valid for new customers only.",
        "expirationDate": "2025-07-31",
        "stackable": False,
        "minimumPurchase": 100,
        "description": "$50 off first plumbing service call for new customers!",
        "offerSource": "installer",
        "redemptionInstructions": "Call (214) 555-BAKER and mention NEW50 promo code.",
        "offerFeatures": [
            "$50 savings",
            "new customer special",
            "24/7 emergency service",
        ],
        "businessName": "Baker Brothers Plumbing, Air & Electric",
        "city": "Dallas",
        "county": "Dallas County",
        "state": "TX",
        "zipcode": "75247",
        "location": None,
        "market": "Dallas-Fort Worth-Arlington, TX Metropolitan Statistical Area",
        "size": "Large",
    },
    {
        "businessId": "bBrP89H32x7y4krCxTujRDRxNqp1m5O8YzUG2Nxc_-W=",
        "url": "https://www.bakerbrothers.com/hvac-services",
        "serviceCategory": "HVAC",
        "discountType": "percentage",
        "discountValue": 10,
        "priceCurrency": "USD",
        "price": None,
        "conditions": "Cannot be combined with other offers.",
        "expirationDate": "2025-10-15",
        "stackable": False,
        "minimumPurchase": None,
        "description": "10% off HVAC system installation or replacement!",
        "offerSource": "installer",
        "redemptionInstructions": "Schedule online or call (214) 555-BAKER. Mention HVAC10.",
        "offerFeatures": [
            "10% discount",
            "professional installation",
            "warranty included",
        ],
        "businessName": "Baker Brothers Plumbing, Air & Electric",
        "city": "Dallas",
        "county": "Dallas County",
        "state": "TX",
        "zipcode": "75247",
        "location": None,
        "market": "Dallas-Fort Worth-Arlington, TX Metropolitan Statistical Area",
        "size": "Large",
    },
    {
        "businessId": "bBrP89H32x7y4krCxTujRDRxNqp1m5O8YzUG2Nxc_-W=",
        "url": "https://www.bakerbrothers.com/electrical-services",
        "serviceCategory": "Electrical",
        "discountType": "amount",
        "discountValue": 100,
        "priceCurrency": "USD",
        "price": None,
        "conditions": "Valid for electrical panel upgrades only.",
        "expirationDate": "2025-11-30",
        "stackable": None,
        "minimumPurchase": 1000,
        "description": "$100 off electrical panel upgrade services!",
        "offerSource": "installer",
        "redemptionInstructions": "Call (214) 555-BAKER to schedule. Mention PANEL100.",
        "offerFeatures": ["$100 savings", "panel upgrade", "code compliance"],
        "businessName": "Baker Brothers Plumbing, Air & Electric",
        "city": "Dallas",
        "county": "Dallas County",
        "state": "TX",
        "zipcode": "75247",
        "location": None,
        "market": "Dallas-Fort Worth-Arlington, TX Metropolitan Statistical Area",
        "size": "Large",
    },
    {
        "businessId": "bBrP89H32x7y4krCxTujRDRxNqp1m5O8YzUG2Nxc_-W=",
        "url": "https://www.bakerbrothers.com/drain-cleaning",
        "serviceCategory": "Plumbing",
        "discountType": "amount",
        "discountValue": None,
        "priceCurrency": "USD",
        "price": 99,
        "conditions": "Standard drain cleaning service only.",
        "expirationDate": "2025-08-30",
        "stackable": None,
        "minimumPurchase": None,
        "description": "Professional drain cleaning service for just $99!",
        "offerSource": "installer",
        "redemptionInstructions": "Call (214) 555-BAKER to schedule drain cleaning.",
        "offerFeatures": [
            "special price",
            "professional equipment",
            "guaranteed results",
        ],
        "businessName": "Baker Brothers Plumbing, Air & Electric",
        "city": "Dallas",
        "county": "Dallas County",
        "state": "TX",
        "zipcode": "75247",
        "location": None,
        "market": "Dallas-Fort Worth-Arlington, TX Metropolitan Statistical Area",
        "size": "Large",
    },
    {
        "businessId": "bBrP89H32x7y4krCxTujRDRxNqp1m5O8YzUG2Nxc_-W=",
        "url": "https://www.bakerbrothers.com/ac-maintenance",
        "serviceCategory": "HVAC",
        "discountType": "amount",
        "discountValue": None,
        "priceCurrency": "USD",
        "price": 79,
        "conditions": "Includes filter replacement and basic inspection.",
        "expirationDate": "2025-09-30",
        "stackable": None,
        "minimumPurchase": None,
        "description": "Complete AC maintenance service for only $79!",
        "offerSource": "installer",
        "redemptionInstructions": "Schedule online or call (214) 555-BAKER for AC maintenance.",
        "offerFeatures": [
            "special price",
            "filter replacement",
            "comprehensive inspection",
        ],
        "businessName": "Baker Brothers Plumbing, Air & Electric",
        "city": "Dallas",
        "county": "Dallas County",
        "state": "TX",
        "zipcode": "75247",
        "location": None,
        "market": "Dallas-Fort Worth-Arlington, TX Metropolitan Statistical Area",
        "size": "Large",
    },
    {
        "businessId": "bTCz63K65g2o8irCxQuiRCRwOro1m7O4XyUF3Nxb_-Y=",
        "url": "https://www.onehourheatandair.com/lees-summit/plumbing-services/",
        "serviceCategory": "Plumbing",
        "discountType": "percentage",
        "discountValue": 20,
        "priceCurrency": "USD",
        "price": None,
        "conditions": "Valid for new customers only. Minimum $150 service.",
        "expirationDate": "2025-06-30",
        "stackable": False,
        "minimumPurchase": 150,
        "description": "20% off your first plumbing service in Lee's Summit!",
        "offerSource": "installer",
        "redemptionInstructions": "Call (816) 354-1077 and mention promo code PLUMB20.",
        "offerFeatures": [
            "20% discount",
            "new customer special",
            "emergency service available",
        ],
        "businessName": "One Hour Heating & Air Conditioning of Lee's Summit",
        "city": "Lee's Summit",
        "county": "Jackson County",
        "state": "MO",
        "zipcode": "64063",
        "location": None,
        "market": "Kansas City, MO-KS Metropolitan Statistical Area",
        "size": "Medium-to-Large",
    },
    {
        "businessId": "bTCz63K65g2o8irCxQuiRCRwOro1m7O4XyUF3Nxb_-Y=",
        "url": "https://www.onehourheatandair.com/lees-summit/hvac-maintenance/",
        "serviceCategory": "HVAC",
        "discountType": "amount",
        "discountValue": 75,
        "priceCurrency": "USD",
        "price": None,
        "conditions": "Cannot be combined with other promotions.",
        "expirationDate": "2025-08-15",
        "stackable": False,
        "minimumPurchase": None,
        "description": "$75 off HVAC tune-up and inspection service!",
        "offerSource": "installer",
        "redemptionInstructions": "Schedule online or call (816) 354-1077.",
        "offerFeatures": [
            "$75 savings",
            "complete HVAC inspection",
            "same day service",
        ],
        "businessName": "One Hour Heating & Air Conditioning of Lee's Summit",
        "city": "Lee's Summit",
        "county": "Jackson County",
        "state": "MO",
        "zipcode": "64063",
        "location": None,
        "market": "Kansas City, MO-KS Metropolitan Statistical Area",
        "size": "Medium-to-Large",
    },
    {
        "businessId": "bTCz63K65g2o8irCxQuiRCRwOro1m7O4XyUF3Nxb_-Y=",
        "url": "https://www.onehourheatandair.com/lees-summit/electrical-services/",
        "serviceCategory": "Electrical",
        "discountType": "percentage",
        "discountValue": 15,
        "priceCurrency": "USD",
        "price": None,
        "conditions": "Valid Monday-Friday only. Excludes weekends and holidays.",
        "expirationDate": "2025-09-30",
        "stackable": None,
        "minimumPurchase": 200,
        "description": "Save 15% on electrical services and repairs!",
        "offerSource": "installer",
        "redemptionInstructions": "Call (816) 354-1077 to schedule. Mention code ELECT15.",
        "offerFeatures": ["15% discount", "licensed electricians", "free estimates"],
        "businessName": "One Hour Heating & Air Conditioning of Lee's Summit",
        "city": "Lee's Summit",
        "county": "Jackson County",
        "state": "MO",
        "zipcode": "64063",
        "location": None,
        "market": "Kansas City, MO-KS Metropolitan Statistical Area",
        "size": "Medium-to-Large",
    },
    {
        "businessId": "bBrP89H32x7y4krCxTujRDRxNqp1m5O8YzUG2Nxc_-W=",
        "url": "https://www.bakerbrothers.com/water-heater-services",
        "serviceCategory": "Plumbing",
        "discountType": "percentage",
        "discountValue": 15,
        "priceCurrency": "USD",
        "price": None,
        "conditions": "Valid for water heater replacement only.",
        "expirationDate": "2025-08-15",
        "stackable": False,
        "minimumPurchase": 500,
        "description": "15% off water heater replacement services!",
        "offerSource": "installer",
        "redemptionInstructions": "Call (214) 555-BAKER for water heater replacement. Mention WH15.",
        "offerFeatures": [
            "15% discount",
            "water heater replacement",
            "professional installation",
        ],
        "businessName": "Baker Brothers Plumbing, Air & Electric",
        "city": "Dallas",
        "county": "Dallas County",
        "state": "TX",
        "zipcode": "75247",
        "location": None,
        "market": "Dallas-Fort Worth-Arlington, TX Metropolitan Statistical Area",
        "size": "Large",
    },
]
